--# PROCESO TERA
DROP TABLE TEMP_TERADATA_V44
CREATE TABLE TEMP_TERADATA_V44
AS
(
SELECT 
(SELECT Max(FECHA_ACT)
FROM AA_LISTA_USER_TABLE_V2) AS FECHA_ACT,
CAST('2021-05-26' AS DATE) AS FECHA_ANT,
Coalesce(A.TABLENAME,B.TABLENAME) AS TABLENAME,
Coalesce(A.CREATORNAME,B.CREATORNAME) AS CREATORNAME,
CASE WHEN A.FECHA_ACT IS NULL THEN 1 ELSE 0 END AS FLAG_ELIM,
CASE WHEN B.FECHA_ACT IS NULL THEN 1 ELSE 0 END AS FLAG_NEW,
Coalesce(A.BYTES_USAGE,0) AS USO_GB_ACT,
Coalesce(B.BYTES_USAGE,0) AS USO_GB_ANT,
USO_GB_ACT-USO_GB_ANT AS DIFF_GB,
(SELECT Max(FECHA_ACT) FROM AA_LISTA_USER_TABLE_V2) - CAST(A.CREATETIMESTAMP AS DATE) AS DIAS_CREA,
(SELECT Max(FECHA_ACT) FROM AA_LISTA_USER_TABLE_V2) - CAST(A.LASTALTERTIMESTAMP AS DATE) AS DIAS_ALTE,
(SELECT Max(FECHA_ACT) FROM AA_LISTA_USER_TABLE_V2) - CAST(A.LASTACCESSTIMESTAMP AS DATE) AS DIAS_CONS
FROM 
(SELECT *
FROM AA_LISTA_USER_TABLE_V2
WHERE FECHA_ACT=(SELECT Max(FECHA_ACT)
FROM AA_LISTA_USER_TABLE_V2)
AND TABLEKIND NOT IN ('P'))A
FULL OUTER JOIN
(SELECT *
FROM AA_LISTA_USER_TABLE_V2
WHERE FECHA_ACT='2021-05-26') B
ON (A.CREATORNAME=B.CREATORNAME
AND A.TABLENAME=B.TABLENAME)
)
WITH DATA PRIMARY INDEX(FECHA_ACT,CREATORNAME,TABLENAME);



CREATE TABLE TEMP_TERADATA_V1
AS
(
SELECT 
DATABASENAME,
Cast(Sum(MAXPERM)/(1024*1024*1024) AS DECIMAL(7,2)) MAX_PERM,
Cast(Sum(CURRENTPERM)/(1024*1024*1024) AS DECIMAL(7,2)) CURRENT_PERM,
Cast(Sum(MAXSPOOL)/(1024*1024*1024) AS DECIMAL(7,2)) MAX_SPOOL,
(MAX_PERM - CURRENT_PERM) AS DISPONIBLE,
Cast(Sum(CURRENTSPOOL)/(1024*1024*1024) AS DECIMAL(7,2)) CURRENT_SPOOL 
FROM 
DBC.DISKSPACE 
WHERE DATABASENAME = 'DBI_MIN' 
GROUP BY 
DATABASENAME
)
WITH DATA PRIMARY INDEX(DATABASENAME);